### ISSUE TITLE
run dvo_slam problem with fuerte 

### ISSUE THREAD

**Issue by lynnsky** [tum-vision/dvo_slam#23]
1.when i run, rosrun dvo_ros camera_tracker
Start dynamic_reconfigure GUI
In /camera_tracker enable reconstruction, use_weighting, run_dense_tracking, and use_dense_tracking_estimate

it get wrong
[ WARN] [1416222358.860807756]: RGB image size has changed, resetting tracker!
Segmentation fault (core dumped)
how to solved it

2.and 
 Start RVIZ
 Set the Target Frame to /world 
I cannot find /world in Target Frame 
how to solved it,thank you

**Comment by tzutalin** [comment]
@wengxiuling36 , 
Did you fix it?
