### ISSUE TITLE
PCL linker issue when compiling jade-devel branch on indigo

### ISSUE THREAD

**Issue by wieset** [tum-vision/dvo_slam#35]
Hi, I tried compiling the new jade-devel branch on indigo (Ubuntu 14.04), since the openni and openni2 packages are still missing in jade. However, I get the following error:

Linking CXX executable /home/tim/catkin_ws/devel/lib/dvo_benchmark/benchmark
/home/tim/catkin_ws/devel/lib/libdvo_visualization.so: undefined reference to `pcl::ApproximateVoxelGridpcl::PointXYZRGB::applyFilter(pcl::PointCloudpcl::PointXYZRGB&)'
collect2: error: ld returned 1 exit status

Does anybody have an idea what's causing this? Wrong version of PCL perhaps?

**Comment by aginika** [comment]
@itsatim I hope you may solve this problem with #36

**Comment by wieset** [comment]
@aginika Awesome, this worked! Now it compiles fine. Thanks a lot :)
