### ISSUE TITLE
ubuntu froze while building dvo_slam

### ISSUE THREAD

**Issue by zenified** [tum-vision/dvo_slam#4]
while building dvo_slam using the command "rosmake dvo_core dvo_ros dvo_slam dvo_benchmark". The system froze while building dvo_slam, 74/76 item completed.

**Comment by christiankerl** [comment]
Does this happen repeatedly? How much RAM do you have? What is file number 74?

**Comment by zenified** [comment]
I believe it might be the RAM issue. The problem  is resolved once I move to a system with higher resources

Thanks
