### ISSUE TITLE
unable to build dvo_core on hydro, missing pcl dependency

### ISSUE THREAD

**Issue by zenified** [tum-vision/dvo_slam#7]
Hi

I been trying to build dvo_slam as per the instruction, however am currently stuck with dvo_core package. 

I was presented with the following error message

```
    [rosbuild] Building package dvo_core Failed to invoke /opt/ros/hydro/bin/rospack deps-manifests dvo_core
    [rospack] Error: package/stack 'dvo_core' depends on non-existent package 'pcl' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'

    CMake Error at /opt/ros/hydro/share/ros/core/rosbuild/public.cmake:129 (message):

   Failed to invoke rospack to get compile flags for package 'dvo_core'.  Look above for errors from rospack itself.  Aborting.  Please fix the broken  dependency!
```

PCl have been installed on by system as per instructed on pcl's site.

I have tried locating the cmake file which configures the directory for PCL but came up empty handed. Perhaps you could point me in the right direction? 

Lastly, I understand that the current release is written for Fuerte, do you think there could be issues with Hydro?

Thanks

**Comment by zenified** [comment]
I found the reason for the error, it is because pcl is no longer packaged by the ROS community  from hydro release of ROS. 

```
       http://www.pcl-users.org/How-do-I-use-PCL-from-ROS-Hydro-td4029613.html
```

To solve this issue just replace in the manifest.xml  

```
    depend package="pcl"
```

with

```
  depend package="pcl_ros"
  depend package="pcl_conversions   
```

I have also had common_rosdeps dependency issues while building, this is cause by common_rosdeps being removed  as of fuerte due to update to rosdeps. Removing
  <depend package="common_rosdeps"/>  
will resolve the issue

**Comment by amesh90** [comment]
thank you it works with me

**Comment by yyxr75** [comment]
hi,

>   [rospack] Error: package 'dvo_core' depends on non-existent package 'commons_rosdep' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
 CMake Error at /opt/ros/kinetic/share/ros/core/rosbuild/public.cmake:129 (message):
  Failed to invoke rospack to get compile flags for package 'dvo_ros'.  Look
    above for errors from rospack itself.  Aborting.  Please fix the broken
    dependency!

How to fix this? thank you all!
